autocmd FileType perl6 iabbrev  <buffer> +-      ±
autocmd FileType perl6 iabbrev  <buffer> sqrt    √
autocmd FileType perl6 iabbrev  <buffer> (o)     ∘
autocmd FileType perl6 iabbrev  <buffer> =~=     ≅
autocmd FileType perl6 iabbrev  <buffer> pi      π
autocmd FileType perl6 iabbrev  <buffer> tau     τ
autocmd FileType perl6 iabbrev  <buffer> (e)     𝑒
autocmd FileType perl6 iabbrev  <buffer> **0     ⁰
autocmd FileType perl6 iabbrev  <buffer> **1     ¹
autocmd FileType perl6 iabbrev  <buffer> **2     ²
autocmd FileType perl6 iabbrev  <buffer> **3     ³
autocmd FileType perl6 iabbrev  <buffer> **4     ⁴
autocmd FileType perl6 iabbrev  <buffer> **5     ⁵
autocmd FileType perl6 iabbrev  <buffer> **6     ⁶
autocmd FileType perl6 iabbrev  <buffer> **7     ⁷
autocmd FileType perl6 iabbrev  <buffer> **8     ⁸
autocmd FileType perl6 iabbrev  <buffer> **9     ⁹
autocmd FileType perl6 iabbrev <buffer> set()   ∅
autocmd FileType perl6 iabbrev <buffer> (elem)  ∈
autocmd FileType perl6 iabbrev <buffer> (E)     ∈
autocmd FileType perl6 iabbrev <buffer> !(elem) ∉ 
autocmd FileType perl6 iabbrev <buffer> (cont)  ∋
autocmd FileType perl6 iabbrev <buffer> !(cont) ∌ 
autocmd FileType perl6 iabbrev <buffer> (<=)    ⊆
autocmd FileType perl6 iabbrev <buffer> !(<=)   ⊈
autocmd FileType perl6 iabbrev <buffer> (<)     ⊂
autocmd FileType perl6 iabbrev <buffer> !(<)    â
autocmd FileType perl6 iabbrev <buffer> (>=)    ⊇
autocmd FileType perl6 iabbrev <buffer> !(>=)   ⊉
autocmd FileType perl6 iabbrev <buffer> (>)     ⊃
autocmd FileType perl6 iabbrev <buffer> !(>)    ⊅
autocmd FileType perl6 iabbrev <buffer> (<+)    ≼
autocmd FileType perl6 iabbrev <buffer> (>+)    ≽
autocmd FileType perl6 iabbrev <buffer> (\|)    ∪
autocmd FileType perl6 iabbrev <buffer> (&)     ∩
autocmd FileType perl6 iabbrev <buffer> (-)     ∖
autocmd FileType perl6 iabbrev <buffer> (^)     ⊖
autocmd FileType perl6 iabbrev <buffer> (.)     ⊍
autocmd FileType perl6 iabbrev <buffer> (+)     ⊎
